---
- name: Add ppa Repository
  sudo: yes
  apt_repository: repo=ppa:chris-lea/redis-server

- name: Update apt
  sudo: yes
  apt: update_cache=yes

- name: Install redis
  sudo: yes
  apt: pkg=redis-server state=latest
